env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - prettier
  - plugin:react/recommended
  - @remix-run/eslint-config
  - @remix-run/eslint-config/node
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
rules:
  "@typescript-eslint/no-var-requires": 0
  "semi": [2, "always"]